@startuml
hide methods
skinparam classAttributeIconSize 0

class Root <<feature>>
class Editors <<group>>
class "BlueJ Code Pad" as BJC <<feature>>
class JShell as JSH <<feature>>
class "Third-party REPL" as TPR <<feature>>

Root *-- Editors
Editors *-- BJC
Editors *-- JSH
Editors *-- TPR

note right of Editors
{xor} exactly one:
- BlueJ Code Pad
- JShell
- Third-party REPL
end note
@enduml
